name = "ad-central-midia-api"
main = "src/index.js"
compatibility_date = "2026-08-01"
workers_dev = true
preview_urls = false

[vars]
SUPABASE_URL = "https://nmprsfrpncquxmutisas.supabase.co"
ALLOWED_ORIGINS = "*"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "ad-central-midia-originals"
